from __future__ import annotations

from collections.abc import Mapping

from packages.common.errors import DomainError

RETRIEVAL_AUTH_REQUIRED = "RETRIEVAL_AUTH_REQUIRED"
RETRIEVAL_INVALID_REQUEST = "RETRIEVAL_INVALID_REQUEST"
RETRIEVAL_FORBIDDEN_FILTER = "RETRIEVAL_FORBIDDEN_FILTER"
RETRIEVAL_EMBEDDING_FAILED = "RETRIEVAL_EMBEDDING_FAILED"
RETRIEVAL_VECTOR_SEARCH_FAILED = "RETRIEVAL_VECTOR_SEARCH_FAILED"
RETRIEVAL_SPARSE_QUERY_INVALID = "RETRIEVAL_SPARSE_QUERY_INVALID"
RETRIEVAL_SPARSE_SEARCH_FAILED = "RETRIEVAL_SPARSE_SEARCH_FAILED"
RETRIEVAL_HYBRID_BRANCH_FAILED = "RETRIEVAL_HYBRID_BRANCH_FAILED"
RETRIEVAL_HYBRID_MERGE_FAILED = "RETRIEVAL_HYBRID_MERGE_FAILED"
RETRIEVAL_RERANK_FAILED = "RETRIEVAL_RERANK_FAILED"
RETRIEVAL_RERANK_DEGRADED = "RETRIEVAL_RERANK_DEGRADED"
RETRIEVAL_RERANK_INVALID_SCORE = "RETRIEVAL_RERANK_INVALID_SCORE"
RETRIEVAL_RERANK_INVALID_CANDIDATE = "RETRIEVAL_RERANK_INVALID_CANDIDATE"
RETRIEVAL_BACKEND_FAILED = "RETRIEVAL_BACKEND_FAILED"


class RetrievalError(DomainError):
    def __init__(
        self,
        *,
        code: str,
        message: str = "Retrieval operation failed.",
        details: Mapping[str, object] | None = None,
        status_code: int = 400,
    ) -> None:
        super().__init__(code=code, message=message, details=details, status_code=status_code)
